name: Greetings
on: 
#  push:
#    branches:
#      - master
  pull_request:
    branches:
      - master
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for creating your first issue on our project. Please allow some time for someone to review your issues.'
        pr-message: 'Thank you for creating your first PR with our project. Please allow time for someone to review your request.'
