name: Mark stale issues and pull requests
on:
  schedule:
    - cron: '0 0 * * 1-7'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been inactive for 5 days and needs some love. Lets see if we can get it resolved.'
          stale-pr-message: 'This PR has been inactive for 5 days and needs some love. Lets see if we can get this approved and merged with the above branch.'
          stale-issue-label: 'low activity'
          stale-pr-label: 'low activity'
          days-before-stale: 5
          exempt-issue-labels: 'blocked,must,should,keep'
