name: Mark stale issues and pull requests
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been inactive and needs some love. Lets see if we can get it resolved.'
          stale-pr-message: 'This PR has been inactive and needs some love. Lets see if we can get this approved and merged with the above branch.'
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
          days-before-stale: 5
          days-before-close: 10
          exempt-issue-labels: 'blocked,must,should,keep'
